### ISSUE TITLE
(website playground) panicked at 'capacity overflow' with using `range`

### ISSUE THREAD

**Issue by qexat** [uiua-lang/uiua#31]
Hi!

I recently discovered uiua through a [code_report video](https://www.youtube.com/watch?v=pq1k5USZZ9A). It looked very interesting so I wanted to try it out. So far it is very fun!

While playing with it, I encountered what I think is a bug:

## Program

In the website playground, I have typed the following program:

```uiua
test ← +⇡
test 15 10

r ← ⇡
r 3
```

## Expected output

```
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[0 1 2]
```

## Actual output

None. Instead, "Running" is being displayed forever.

## Console

The following errors are printed:

```
site-11b5530f73ff5e21.js:384 panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:524:5
```

```
Uncaught RuntimeError: unreachable
```

Full traceback: [www.uiua.org-1696081573340.txt](https://github.com/uiua-lang/uiua/files/12774812/www.uiua.org-1696081573340.txt)

## Specs

Browser: Google Chrome 118.0.5993.32 (Official Build) beta (64-bit)

---

Hopefully, this report gives enough information to be useful. Thank you in advance for your response!

**Comment by qexat** [comment]
For some reason, the traceback doesn't display in my browser, and gets downloaded instead. In case it also happens to you, I'm writing it down here:

```
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'attribution-reporting'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'run-ad-auction'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'join-ad-interest-group'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'browsing-topics'.
site-11b5530f73ff5e21.js:384 panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:524:5

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (https://www.uiua.org/site-11b5530f73ff5e21.js:371:21)
    at console_error_panic_hook::hook::h51324b83e5e34372 (https://www.uiua.org/site-11b5530f73ff5e21_bg.wasm:wasm-function[1407]:0x51c825)
    at std::panicking::rust_panic_with_hook::h7601402c0a383194 (https://www.uiua.org/site-11b5530f73ff5e21_bg.wasm:wasm-function[2877]:0x5b10e3)
    at std::panicking::begin_panic_handler::{{closure}}::he405aaeb801d5772 (https://www.uiua.org/site-11b5530f73ff5e21_bg.wasm:wasm-function[3070]:0x5b99f7)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h04fac26f88d230df (https://www.uiua.org/site-11b5530f73ff5e21_bg.wasm:wasm-function[4139]:0x5ccf0b)
    at rust_begin_unwind (https://www.uiua.org/site-11b5530f73ff5e21_bg.wasm:wasm-function[3666]:0x5c90b8)
    at core::panicking::panic_fmt::h6dad0405f48e39e2 (https://www.uiua.org/site-11b5530f73ff5e21_bg.wasm:wasm-function[3701]:0x5c9974)
    at alloc::raw_vec::capacity_overflow::h69391d2b6a90e408 (https://www.uiua.org/site-11b5530f73ff5e21_bg.wasm:wasm-function[3702]:0x5c99b5)
    at uiua::algorithm::monadic::<impl uiua::value::Value>::range::h7e1f486fde846fe8 (https://www.uiua.org/site-11b5530f73ff5e21_bg.wasm:wasm-function[1011]:0x4ab87d)
    at uiua::run::Uiua::monadic_ref_env::h960e6a5f0cf0af95 (https://www.uiua.org/site-11b5530f73ff5e21_bg.wasm:wasm-function[1396]:0x51a2f7)


imports.wbg.__wbg_error_f851667af71bcfc6 @ site-11b5530f73ff5e21.js:384
$console_error_panic_hook::hook::h51324b83e5e34372 @ site-11b5530f73ff5e21_bg.wasm:0x51c92e
$std::panicking::rust_panic_with_hook::h7601402c0a383194 @ site-11b5530f73ff5e21_bg.wasm:0x5b10e3
$std::panicking::begin_panic_handler::{{closure}}::he405aaeb801d5772 @ site-11b5530f73ff5e21_bg.wasm:0x5b99f7
$std::sys_common::backtrace::__rust_end_short_backtrace::h04fac26f88d230df @ site-11b5530f73ff5e21_bg.wasm:0x5ccf0b
$rust_begin_unwind @ site-11b5530f73ff5e21_bg.wasm:0x5c90b8
$core::panicking::panic_fmt::h6dad0405f48e39e2 @ site-11b5530f73ff5e21_bg.wasm:0x5c9974
$alloc::raw_vec::capacity_overflow::h69391d2b6a90e408 @ site-11b5530f73ff5e21_bg.wasm:0x5c99b5
$uiua::algorithm::monadic::<impl uiua::value::Value>::range::h7e1f486fde846fe8 @ site-11b5530f73ff5e21_bg.wasm:0x4ab87d
$uiua::run::Uiua::monadic_ref_env::h960e6a5f0cf0af95 @ site-11b5530f73ff5e21_bg.wasm:0x51a2f7
$uiua::primitive::<impl uiua::primitive::defs::Primitive>::run::hd4b94cf597e0605f @ site-11b5530f73ff5e21_bg.wasm:0xdb011
$uiua::run::Uiua::exec::hdb461013f0e0edb0 @ site-11b5530f73ff5e21_bg.wasm:0x2e4d15
$uiua::run::Uiua::items::he39bd0a2e8b1429b @ site-11b5530f73ff5e21_bg.wasm:0x308660
$uiua::run::Uiua::load_impl::h6777819d28dd341b @ site-11b5530f73ff5e21_bg.wasm:0x4089ca
$<T as wasm_bindgen::closure::WasmClosureFnOnce<(),R>>::into_js_function::{{closure}}::h5945562356025c85 @ site-11b5530f73ff5e21_bg.wasm:0x265892
$wasm_bindgen::convert::closures::invoke0_mut::h07ae13365438c52e @ site-11b5530f73ff5e21_bg.wasm:0x5cb9a6
__wbg_adapter_41 @ site-11b5530f73ff5e21.js:221
real @ site-11b5530f73ff5e21.js:202
setTimeout (async)
(anonymous) @ site-11b5530f73ff5e21.js:528
handleError @ site-11b5530f73ff5e21.js:234
imports.wbg.__wbg_setTimeout_eb1a0d116c26d9f6 @ site-11b5530f73ff5e21.js:527
$leptos_dom::helpers::set_timeout_with_handle::st::h84380f142ed1d7f7 @ site-11b5530f73ff5e21_bg.wasm:0x5c3486
$leptos_dom::helpers::window_event_listener::{{closure}}::ha6a53b792a140d78 @ site-11b5530f73ff5e21_bg.wasm:0x290321
$wasm_bindgen::convert::closures::invoke1_mut::h00d44d9c5034da05 @ site-11b5530f73ff5e21_bg.wasm:0x5cb85a
__wbg_adapter_34 @ site-11b5530f73ff5e21.js:217
real @ site-11b5530f73ff5e21.js:202
site-11b5530f73ff5e21_bg.wasm:0x5ccfeb Uncaught RuntimeError: unreachable
    at rust_panic (site-11b5530f73ff5e21_bg.wasm:0x5ccfeb)
    at std::panicking::rust_panic_with_hook::h7601402c0a383194 (site-11b5530f73ff5e21_bg.wasm:0x5b110c)
    at std::panicking::begin_panic_handler::{{closure}}::he405aaeb801d5772 (site-11b5530f73ff5e21_bg.wasm:0x5b99f7)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h04fac26f88d230df (site-11b5530f73ff5e21_bg.wasm:0x5ccf0b)
    at rust_begin_unwind (site-11b5530f73ff5e21_bg.wasm:0x5c90b8)
    at core::panicking::panic_fmt::h6dad0405f48e39e2 (site-11b5530f73ff5e21_bg.wasm:0x5c9974)
    at alloc::raw_vec::capacity_overflow::h69391d2b6a90e408 (site-11b5530f73ff5e21_bg.wasm:0x5c99b5)
    at uiua::algorithm::monadic::<impl uiua::value::Value>::range::h7e1f486fde846fe8 (site-11b5530f73ff5e21_bg.wasm:0x4ab87d)
    at uiua::run::Uiua::monadic_ref_env::h960e6a5f0cf0af95 (site-11b5530f73ff5e21_bg.wasm:0x51a2f7)
    at uiua::primitive::<impl uiua::primitive::defs::Primitive>::run::hd4b94cf597e0605f (site-11b5530f73ff5e21_bg.wasm:0xdb011)
$rust_panic @ site-11b5530f73ff5e21_bg.wasm:0x5ccfeb
$std::panicking::rust_panic_with_hook::h7601402c0a383194 @ site-11b5530f73ff5e21_bg.wasm:0x5b110c
$std::panicking::begin_panic_handler::{{closure}}::he405aaeb801d5772 @ site-11b5530f73ff5e21_bg.wasm:0x5b99f7
$std::sys_common::backtrace::__rust_end_short_backtrace::h04fac26f88d230df @ site-11b5530f73ff5e21_bg.wasm:0x5ccf0b
$rust_begin_unwind @ site-11b5530f73ff5e21_bg.wasm:0x5c90b8
$core::panicking::panic_fmt::h6dad0405f48e39e2 @ site-11b5530f73ff5e21_bg.wasm:0x5c9974
$alloc::raw_vec::capacity_overflow::h69391d2b6a90e408 @ site-11b5530f73ff5e21_bg.wasm:0x5c99b5
$uiua::algorithm::monadic::<impl uiua::value::Value>::range::h7e1f486fde846fe8 @ site-11b5530f73ff5e21_bg.wasm:0x4ab87d
$uiua::run::Uiua::monadic_ref_env::h960e6a5f0cf0af95 @ site-11b5530f73ff5e21_bg.wasm:0x51a2f7
$uiua::primitive::<impl uiua::primitive::defs::Primitive>::run::hd4b94cf597e0605f @ site-11b5530f73ff5e21_bg.wasm:0xdb011
$uiua::run::Uiua::exec::hdb461013f0e0edb0 @ site-11b5530f73ff5e21_bg.wasm:0x2e4d15
$uiua::run::Uiua::items::he39bd0a2e8b1429b @ site-11b5530f73ff5e21_bg.wasm:0x308660
$uiua::run::Uiua::load_impl::h6777819d28dd341b @ site-11b5530f73ff5e21_bg.wasm:0x4089ca
$<T as wasm_bindgen::closure::WasmClosureFnOnce<(),R>>::into_js_function::{{closure}}::h5945562356025c85 @ site-11b5530f73ff5e21_bg.wasm:0x265892
$wasm_bindgen::convert::closures::invoke0_mut::h07ae13365438c52e @ site-11b5530f73ff5e21_bg.wasm:0x5cb9a6
__wbg_adapter_41 @ site-11b5530f73ff5e21.js:221
real @ site-11b5530f73ff5e21.js:202
setTimeout (async)
(anonymous) @ site-11b5530f73ff5e21.js:528
handleError @ site-11b5530f73ff5e21.js:234
imports.wbg.__wbg_setTimeout_eb1a0d116c26d9f6 @ site-11b5530f73ff5e21.js:527
$leptos_dom::helpers::set_timeout_with_handle::st::h84380f142ed1d7f7 @ site-11b5530f73ff5e21_bg.wasm:0x5c3486
$leptos_dom::helpers::window_event_listener::{{closure}}::ha6a53b792a140d78 @ site-11b5530f73ff5e21_bg.wasm:0x290321
$wasm_bindgen::convert::closures::invoke1_mut::h00d44d9c5034da05 @ site-11b5530f73ff5e21_bg.wasm:0x5cb85a
__wbg_adapter_34 @ site-11b5530f73ff5e21.js:217
real @ site-11b5530f73ff5e21.js:202
```

**Comment by kaikalii** [comment]
So, the reason you hit this bug has to do with the line
```
r ← ⇡
```
You already had that big array on the stack, and it tried to make a range from that which would be way too big.
Multiplication overflowed and crashed the interpreter.

c1c974c88f814 makes it catch the overflow and return an error.

I'm going to leave this open for now, because it's true that this behavior is very unintuitive, and the way that bindings work probably needs to be reworked to avoid this.

**Comment by kaikalii** [comment]
I have improved the way that bindings work to make them independent of what is already on the stack.

As of ac86db4024309, your example
```
test ← +⇡
test 15 10

r ← ⇡
r 3
```
now produces the outputs you expected.

**Comment by qexat** [comment]
Thank you very much!
